# Generated by Django 4.0.2 on 2022-03-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cctr', models.CharField(blank=True, max_length=2000, null=True)),
                ('currency', models.CharField(choices=[('Etherum', 'Etherum'), ('Dollars', 'Dollars'), ('Euro', 'Euro'), ('Bitcoin', 'Bitcoin'), ('Pounds Sterling', 'Pounds Sterling'), ('Naira', 'Naira')], max_length=2000)),
                ('comment', models.TextField(blank=True, max_length=2000, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=2000, null=True)),
                ('Vatchoice', models.CharField(choices=[('Exclusive', 'Exclusive'), ('Inclusive', 'Inclusive')], max_length=2000, null=True)),
                ('VAT', models.CharField(blank=True, max_length=2000, null=True)),
                ('total', models.CharField(blank=True, max_length=2000, null=True)),
                ('pmode', models.CharField(choices=[('Cash', 'Cash'), ('Electronic', 'Electronic'), ('Cheque', 'Cheque')], max_length=2000)),
                ('beneficiary', models.CharField(blank=True, max_length=2000, null=True)),
                ('bacctinfo', models.CharField(blank=True, max_length=2000, null=True)),
                ('others', models.CharField(blank=True, max_length=2000, null=True)),
                ('mdate', models.CharField(blank=True, max_length=2000, null=True)),
                ('fdate', models.CharField(blank=True, max_length=2000, null=True)),
                ('rdetails', models.CharField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=2000, null=True)),
                ('fstatus', models.CharField(blank=True, default='Pending', max_length=2000, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_fapproved', models.BooleanField(default=False)),
                ('pstatus', models.BooleanField(default=False)),
                ('Finance_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fmapprover', to=settings.AUTH_USER_MODEL)),
                ('Manager_approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfapprover', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfname', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'RequestForm',
                'verbose_name_plural': 'RequestForms',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RFsummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('project', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('rf', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requestform', to='forms.requestform')),
            ],
        ),
        migrations.CreateModel(
            name='Purchaseorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_to', models.CharField(blank=True, max_length=2000, null=True)),
                ('order_no', models.CharField(blank=True, max_length=2000, null=True)),
                ('ship_to', models.CharField(blank=True, max_length=2000, null=True)),
                ('payment_terms', models.CharField(blank=True, max_length=2000, null=True)),
                ('delivery_date', models.DateField(blank=True, max_length=2000, null=True)),
                ('subtotal', models.CharField(blank=True, max_length=2000, null=True)),
                ('Vatchoice', models.CharField(choices=[('Exclusive', 'Exclusive'), ('Inclusive', 'Inclusive')], max_length=2000, null=True)),
                ('VAT', models.CharField(blank=True, max_length=2000, null=True)),
                ('freight', models.CharField(blank=True, max_length=2000, null=True)),
                ('total', models.CharField(blank=True, max_length=2000, null=True)),
                ('remarks', models.TextField(blank=True, max_length=2000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, default='Pending', max_length=2000, null=True)),
                ('mdate', models.CharField(blank=True, max_length=2000, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchaseorder',
                'verbose_name_plural': 'Purchaseorders',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Ordersummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('project', models.CharField(blank=True, max_length=2000, null=True)),
                ('quantity', models.IntegerField(blank=True, default='0', null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('po', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseorder', to='forms.purchaseorder')),
            ],
        ),
    ]
