# Generated by Django 4.0.2 on 2022-03-10 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestform',
            name='currency',
            field=models.CharField(choices=[('Bitcoin', 'Bitcoin'), ('Dollars', 'Dollars'), ('Etherum', 'Etherum'), ('Pounds Sterling', 'Pounds Sterling'), ('Naira', 'Naira'), ('Euro', 'Euro')], max_length=2000),
        ),
        migrations.AlterField(
            model_name='requestform',
            name='pmode',
            field=models.CharField(choices=[('Electronic', 'Electronic'), ('Cash', 'Cash'), ('Cheque', 'Cheque')], max_length=2000),
        ),
    ]
