# Generated by Django 4.0.2 on 2022-03-10 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, null=True, verbose_name='Name of Bank')),
                ('account', models.CharField(help_text='employee account number', max_length=30, null=True, verbose_name='Account Number')),
                ('branch', models.CharField(blank=True, help_text='which branch was the account issue', max_length=125, null=True, verbose_name='Branch')),
                ('salary', models.DecimalField(decimal_places=2, help_text='This is the initial salary of employee', max_digits=16, null=True, verbose_name='Starting Salary')),
                ('basic', models.CharField(max_length=250)),
                ('housing', models.CharField(max_length=250)),
                ('transport', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['-name', '-account'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.CharField(blank=True, max_length=125, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name', 'created'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr'), ('MRS', 'Mrs'), ('MISS', 'Miss'), ('DR', 'Dr'), ('SIR', 'Sir'), ('MADAM', 'Madam')], default='Mr', max_length=5, null=True, verbose_name='Title')),
                ('image', models.ImageField(blank=True, default='profile.png', help_text='upload image size less than 2.0MB', null=True, upload_to='', verbose_name='Profile Image')),
                ('firstname', models.CharField(max_length=125, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=125, verbose_name='Lastname')),
                ('othername', models.CharField(blank=True, max_length=125, null=True, verbose_name='Othername (optional)')),
                ('sex', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other'), ('NOT_KNOWN', 'Not Known')], default='Male', max_length=9, verbose_name='Gender')),
                ('email', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Email (optional)')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+234240000000', help_text='Enter number with Country Code Eg. +234240000000', max_length=128, region=None, verbose_name='Phone Number (Example +234240000000)')),
                ('bio', models.CharField(blank=True, default='', help_text='Tell us something about yourself eg. i love eating ...', max_length=255, null=True, verbose_name='Bio')),
                ('birthday', models.DateField(verbose_name='Birthday')),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity'), ('Other', 'Other')], default=None, max_length=125, null=True, verbose_name='Religion')),
                ('nationality', models.CharField(default=None, max_length=125, null=True, verbose_name='Nationality')),
                ('hometown', models.CharField(blank=True, max_length=125, null=True, verbose_name='Hometown')),
                ('residence', models.CharField(max_length=125, verbose_name='Current Residence')),
                ('address', models.CharField(blank=True, help_text='address of current residence', max_length=125, null=True, verbose_name='Address')),
                ('education', models.CharField(choices=[('SENIORHIGH', 'Senior High School'), ('JUNIORHIGH', 'Junior High School'), ('PRIMARY', 'Primary School'), ('TERTIARY', 'Tertiary/University/Polytechnic'), ('OLEVEL', 'OLevel'), ('OTHER', 'Other')], default='Senior_High', help_text='highest educational standard ie. your last level of schooling', max_length=20, null=True, verbose_name='Education')),
                ('lastwork', models.CharField(blank=True, help_text='Employees Last place of Work', max_length=125, null=True, verbose_name='Last Place of Work')),
                ('position', models.CharField(blank=True, help_text='Employees position at last place of work', max_length=255, null=True, verbose_name='Position Held')),
                ('ssnitnumber', models.CharField(blank=True, max_length=30, null=True, verbose_name='SSNIT Number')),
                ('tinnumber', models.CharField(blank=True, max_length=15, null=True, verbose_name='TIN')),
                ('role', models.CharField(help_text='Position Held', max_length=255, null=True, verbose_name='Position Held')),
                ('startdate', models.DateField(help_text='Date of Employment', null=True, verbose_name='Employement Date')),
                ('employeetype', models.CharField(choices=[('Full Time', 'Full-Time'), ('Part Time', 'Part-Time'), ('Contract', 'Contract'), ('Intern', 'Intern')], default='Full_Time', max_length=15, null=True, verbose_name='Employee Type')),
                ('employeeid', models.CharField(blank=True, help_text='Enter 5 characters, First and Last Letter of the department in caps followed by 3 numbers. e.g Finance (FE001)', max_length=11, null=True, verbose_name='Employee ID Number')),
                ('dateissued', models.DateField(help_text='Date Employee id was issued', null=True, verbose_name='Date Issued')),
                ('is_blocked', models.BooleanField(default=False, help_text='button to toggle employee block and unblock', verbose_name='Is Blocked')),
                ('is_deleted', models.BooleanField(default=False, help_text='button to toggle employee deleted and undelete', verbose_name='Is Deleted')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('department', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.department', verbose_name='Department')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widow', 'Widow'), ('Widower', 'Widower')], default='Single', max_length=10, null=True, verbose_name='Marital Status')),
                ('spouse', models.CharField(blank=True, max_length=255, null=True, verbose_name='Spouse (Fullname)')),
                ('occupation', models.CharField(blank=True, help_text='spouse occupation', max_length=125, null=True, verbose_name='Occupation')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, help_text='Enter number with Country Code Eg. +234240000000', max_length=128, null=True, region=None, verbose_name='Spouse Phone Number (Example +234240000000)')),
                ('children', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Children')),
                ('nextofkin', models.CharField(help_text='fullname of next of kin', max_length=255, null=True, verbose_name='Next of Kin')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Phone Number of Next of Kin', max_length=128, null=True, region=None, verbose_name='Next of Kin Phone Number (Example +233240000000)')),
                ('relationship', models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Sister', 'Sister'), ('Brother', 'Brother'), ('Uncle', 'Uncle'), ('Aunty', 'Aunty'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Fiance', 'Fiance'), ('Cousin', 'Cousin'), ('Fiancee', 'Fiancee'), ('Niece', 'Niece'), ('Nephew', 'Nephew'), ('Son', 'Son'), ('Daughter', 'Daughter')], help_text='Who is this person to you ?', max_length=15, null=True, verbose_name='Relationship with Next of Person')),
                ('father', models.CharField(blank=True, max_length=255, null=True, verbose_name="Father's Name")),
                ('foccupation', models.CharField(blank=True, max_length=125, null=True, verbose_name="Father's Occupation")),
                ('mother', models.CharField(blank=True, max_length=255, null=True, verbose_name="Mother's Name")),
                ('moccupation', models.CharField(blank=True, max_length=125, null=True, verbose_name="Mother's Occupation")),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Relationship',
                'verbose_name_plural': 'Relationships',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentdate', models.DateField(blank=True, max_length=250)),
                ('overtime', models.CharField(blank=True, default=0, max_length=250)),
                ('basic_m', models.CharField(max_length=250)),
                ('housing_m', models.CharField(max_length=250)),
                ('transport_m', models.CharField(max_length=250)),
                ('pension', models.CharField(blank=True, max_length=250)),
                ('paye', models.CharField(max_length=250)),
                ('loan', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('bonus', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('gross', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('totald', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('netpay', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('deductther', models.CharField(blank=True, default=0, max_length=250, null=True)),
                ('month', models.CharField(blank=True, choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=250, null=True)),
                ('Year', models.CharField(blank=True, choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031')], max_length=250, null=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.bank')),
                ('employ', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(help_text='who should we contact ?', max_length=255, null=True, verbose_name='Fullname')),
                ('tel', phonenumber_field.modelfields.PhoneNumberField(default='+234240000000', help_text='Enter number with Country Code Eg. +234240000000', max_length=128, region=None, verbose_name='Phone Number (Example +234240000000)')),
                ('location', models.CharField(max_length=125, null=True, verbose_name='Place of Residence')),
                ('relationship', models.CharField(choices=[('FATHER', 'Father'), ('MOTHER', 'Mother'), ('SIS', 'Sister'), ('BRO', 'Brother'), ('UNCLE', 'Uncle'), ('AUNTY', 'Aunty'), ('HUSBAND', 'Husband'), ('WIFE', 'Wife'), ('FIANCE', 'Fiance'), ('COUSIN', 'Cousin'), ('FIANCEE', 'Fiancee'), ('NIECE', 'Niece'), ('NEPHEW', 'Nephew'), ('SON', 'Son'), ('DAUGHTER', 'Daughter')], default='Father', help_text='Who is this person to you ?', max_length=8, null=True, verbose_name='Relationship with Person')),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'verbose_name': 'Emergency',
                'verbose_name_plural': 'Emergency',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='bank',
            name='employee',
            field=models.ForeignKey(help_text='select employee(s) to add bank account', null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
